version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:${DB_VERSION}-${DB_VERSION_VARIANTE}
    tty: true
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./${DB_VOLUMEN_PATH}:/var/lib/postgresql/data/
      - ./db:/docker-entrypoint-initdb.d/
